---
title: "Darwin Core update"
author: "Michael Maniscalco"
date: '2022-07-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(lubridate)
library(janitor)
library(googlesheets4)
```

# This script will load remote data of darwin core files currently in EDI database along with new data and put it together into new darwin core files

### Read in data
* could change paths to EDI links rather than gdrive

```{r read }

googlesheets4::gs4_auth(path = '.secrets/enduring-coil-349821-3832e38b5b43.json')

df_event <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1BaCEGePEYx9wbduccHytb9uRVbz3447GEDCE8Hpm0I8/edit#gid=1448123747",
                                      sheet="Event")

df_phyto <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1BaCEGePEYx9wbduccHytb9uRVbz3447GEDCE8Hpm0I8/edit#gid=1550025152",
                                      sheet="Occurrence")

# ## env
df_envir <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1BaCEGePEYx9wbduccHytb9uRVbz3447GEDCE8Hpm0I8/edit#gid=1448123747",
                                      sheet="Extended")
```

```{r format}
df_phyto_wide <- df_phyto %>%
  select(-c(occurrenceID:kingdom)) %>%
  tidyr::pivot_wider(.,names_from = organismName,values_from = organismQuantity)

df_envir_wide <- df_envir %>%
  select(-c(measurementID:measurementRemarks)) %>%
  tidyr::pivot_wider(.,names_from = measurementType,values_from = measurementValue)

historical_wide <- left_join(df_event,df_envir_wide) %>%
  left_join(.,df_phyto_wide) %>%
  relocate(monitor_names, .after="eventRemarks")%>%
  relocate(descending_transparency:ascending_transparency, .before="transparency_depth_mean") %>%
  mutate(across(c(air_temp:water_temp, wind_speed_knots,
                  tide_height:bod, pH, bottom_depth_m,
                   wind_direction), ~as.numeric(.x))) %>%
  mutate(time_high_tide=as.POSIXct(time_high_tide,
                                   format="%Y-%m-%d %H:%M:%S",
                                   tz ="UTC"),
         time_low_tide=as.POSIXct(time_low_tide,
                                  format="%Y-%m-%d %H:%M:%S",
                                  tz ="UTC")) 
tax_table <- read_csv("source_data/tax_table.csv")

df_new <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1JGXLAvG_U9dWn7Ya_NorUU3mcgpi7aX2uanszfhXP8c/edit?sharingaction=ownershiptransfer#gid=0",
                                    sheet = "processed") %>%
  dplyr::mutate(across(c(water_temp:air_temp,rainfall_mm,
                         wind_speed_knots,
                         ascending_transparency:nutrient_vial_id, 
                         wind_direction),
                       ~as.numeric(.x)))%>%
  dplyr::select(-c(Copepods, Other_zooplankton, Total_zooplankton, sampling_method)) %>%
  dplyr::mutate(maximumDepthInMeters=ifelse(is.na(maximumDepthInMeters)==T,
                                            1,
                                            maximumDepthInMeters),
                minimumDepthInMeters=ifelse(is.na(minimumDepthInMeters)==T,
                                            0.5,
                                            minimumDepthInMeters)) 
### wide
df_full <- full_join(historical_wide,df_new)
rm(df_new,historical_wide, df_event, df_phyto, df_envir, df_phyto_wide ,df_envir_wide)
```

### Darwin core Occurrence

```{r Occur}
df_full_occurrence <- df_full %>%
  rowwise() %>%
  tidyr::pivot_longer(., cols=(Alexandrium:Total_phytoplankton),
                      names_to = "organismName",
                      values_to = "organismQuantity") %>%
  dplyr::left_join(.,tax_table, by="organismName") %>%
  dplyr::mutate(occurrenceID=paste(strftime(eventDate, "%Y-%m-%dT%H:%M:%S%Z", tz = "Zulu"), organismName, sep="_")) %>%
  dplyr::mutate(occurrenceStatus= ifelse(organismQuantity>0, "present", "absent")) %>%
  dplyr::select(id, basisOfRecord, organismName, organismQuantity, organismQuantityType,
                occurrenceID, occurrenceStatus, scientificName, scientificNameID, taxonID, kingdom) %>%
  dplyr::filter_at(vars(occurrenceStatus), all_vars(!is.na(.))) 

### add new file name/location
write_csv(df_full_occurrence,"")
```

### Darwin core Events

```{r event}
df_full_events <- df_full %>%
  select(id, eventID,	eventDate, geodeticDatum,	countryCode, locationID, 
         eventRemarks,	decimalLatitude,	decimalLongitude,	minimumDepthInMeters,
         maximumDepthInMeters,	coordinateUncertaintyInMeters)%>%
  arrange(eventDate)

### add new file name/location
write_csv(df_full_events,"")
```

### Make ExtendedMeasurementOrFact

```{r extended}
### Darwin core Extended
extended_base <- read_csv("source_data/columns_units.csv") %>%
  filter(darwin_file=="all"|darwin_file=="ExtendedMeasurementOrFact")

phyto_extended <- df_full %>%
  select(-eventRemarks, -nutrient_vial_id, 
         -c(Alexandrium:Other_phytoplankton)) %>% 
  mutate(across(air_temp:transparency_depth_mean, ~as.character(.x))) %>%
  pivot_longer(., 
               cols=(time_low_tide:pH),
               names_to = "measurementType",
               values_to = "measurementValue",
               values_transform = list(measurementValue = as.character)) %>%
  mutate(measurementValue=ifelse(measurementType=="rainfall_mm" & measurementValue=="0",
                                 NA, 
                                 measurementValue)) %>%
  filter(!is.na(measurementValue)) %>%
  left_join(., extended_base, by= "measurementType") %>%
  select(.,id, measurementType,	measurementValue,	measurementID,
         measurementTypeID,	measurementUnit,
         measurementUnitID, # is this one optional?
         measurementRemarks) %>%
  arrange(id)

### add new file name/location
write_csv(phyto_extended,"")
```




